### ISSUE TITLE
federation protocol support 

### ISSUE THREAD

**Issue by manran** [WilsonHua/stellarPay#1]
[联邦协议](https://www.stellar.org/developers/guides/concepts/federation.html)可以很方便的添加锚点，可以参考一下[stellarterm](https://stellarterm.com)，它实现了联邦协议。

**Comment by WilsonHua** [comment]
好的，当时做的时候时间比较急，所以没有做得很完善，最近有时间会把功能慢慢加上，修改一下bug。多谢丰哥提醒！

2017-01-26 9:58 GMT+08:00 Eno <notifications@github.com>:
